### ISSUE TITLE
error in Drawing.cs

### ISSUE THREAD

**Issue by bdbabiak** [EMJK/hive#1]
It compiles perfectly all test, except the following 2 lines in Drawing.cs where it says:

C:\Users\Brian Babiak MD\Documents\GitHub\hive\Graphics\Drawing.cs(26,22,26,35): error CS0103: The name 'PrimitiveType' does not exist in the current context
1>C:\Users\Brian Babiak MD\Documents\GitHub\hive\Graphics\Drawing.cs(58,22,58,35): error CS0103: The name 'PrimitiveType' does not exist in the current context

Otherwise perfect. No problem. Any ideas?

**Comment by julkwiec** [comment]
Hi,
The GUI part is being redone with Unity. For now I've removed the current graphics code.
